version: "3.7"
services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - "${PWD}/db-data:/var/lib/postgresql/data"

  local-runner:
    image: amazon/mwaa-local:2_10
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - "${PWD}/../contrib/.kube/config:/usr/local/airflow/dags/.kube/config"
      - "${PWD}/../contrib/airflow/airflow_local_settings.py:/usr/local/airflow/airflow_local_settings.py"
      - "${PWD}/../contrib/plugins:/usr/local/airflow/plugins"
      - "${PWD}/../contrib/dag_factory/dag_factory.py:/usr/local/airflow/dags/dag_factory.py"
      - "${PWD}/../dist/dags/development:/usr/local/airflow/dags/development"
      - "${PWD}/../requirements.txt:/usr/local/airflow/requirements/requirements.txt"
      - "${PWD}/startup_script:/usr/local/airflow/startup"
    ports:
      - "8080:8080"
    command: local-runner
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    env_file:
      - ./config/.env.localrunner
